MODEL:
  TYPE: swin
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.0
  NUM_CLASSES: 8
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [4, 8, 16, 32]
    WINDOW_SIZE: 16
    PATCH_SIZE: 4
    IN_CHANS: 3
DATA:
  IMG_SIZE: 512
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6